name: Run MATLAB Build
on: [push, pull_request]
jobs:
  run-tests:
    name: Run Simulink Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Run Tests
        uses: matlab-actions/run-command@v1
        with:
          command: buildtool test
  run-checks:
    name: Run Model Advisor Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Run Checks
        uses: matlab-actions/run-command@v1
        with:
          command: buildtool check
